galaxy_info:
  role_name: ludus_emprange_web
  author: l3xic0n
  description: Deploys intranet site content on top of geerlingguy.apache for the EMP AD range
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [bookworm]
dependencies: []
